/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wyvutcmmzwovspogeijk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dnV0Y21tendvdnNwb2dlaWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NzM3NTEsImV4cCI6MjA3NjE0OTc1MX0.8F3JL-ybarQBcj-NGYMZXcFBMwTMu1V9kmIXytdkdJo"